package protofields

import (
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/datatypes_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/account_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/activity_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/adverse_event_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/allergy_intolerance_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/appointment_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/appointment_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/audit_event_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/basic_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/binary_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/biologically_derived_product_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/body_structure_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/bundle_and_contained_resource_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/capability_statement_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/care_plan_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/care_team_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/catalog_entry_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/charge_item_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/charge_item_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/claim_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/claim_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/clinical_impression_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/code_system_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/communication_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/communication_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/compartment_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/composition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/concept_map_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/condition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/consent_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/contract_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/coverage_eligibility_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/coverage_eligibility_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/coverage_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/detected_issue_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/device_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/device_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/device_metric_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/device_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/device_use_statement_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/diagnostic_report_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/document_manifest_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/document_reference_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/effect_evidence_synthesis_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/encounter_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/endpoint_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/enrollment_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/enrollment_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/episode_of_care_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/event_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/evidence_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/evidence_variable_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/example_scenario_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/explanation_of_benefit_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/family_member_history_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/flag_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/goal_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/graph_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/group_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/guidance_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/healthcare_service_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/imaging_study_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/immunization_evaluation_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/immunization_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/immunization_recommendation_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/implementation_guide_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/insurance_plan_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/invoice_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/library_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/linkage_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/list_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/location_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/measure_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/measure_report_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/media_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_administration_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_dispense_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_knowledge_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medication_statement_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_authorization_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_contraindication_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_indication_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_ingredient_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_interaction_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_manufactured_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_packaged_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_pharmaceutical_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/medicinal_product_undesirable_effect_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/message_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/message_header_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/molecular_sequence_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/naming_system_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/nutrition_order_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/observation_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/observation_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/operation_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/operation_outcome_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/organization_affiliation_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/organization_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/parameters_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/patient_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/payment_notice_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/payment_reconciliation_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/person_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/plan_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/practitioner_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/practitioner_role_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/procedure_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/provenance_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/questionnaire_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/questionnaire_response_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/related_person_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/request_group_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/research_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/research_element_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/research_study_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/research_subject_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/risk_assessment_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/risk_evidence_synthesis_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/schedule_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/search_parameter_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/service_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/slot_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/specimen_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/specimen_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/structure_definition_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/structure_map_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/subscription_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_nucleic_acid_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_polymer_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_protein_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_reference_information_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_source_material_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/substance_specification_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/supply_delivery_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/supply_request_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/task_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/terminology_capabilities_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/test_report_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/test_script_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/value_set_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/verification_result_go_proto"
	"github.com/google/fhir/go/proto/google/fhir/proto/r4/core/resources/vision_prescription_go_proto"
	"google.golang.org/protobuf/proto"
)

// dummyResources is an array of nil pointers to all resource messages.
var dummyResources = []proto.Message{
	(*account_go_proto.Account)(nil),
	(*activity_definition_go_proto.ActivityDefinition)(nil),
	(*adverse_event_go_proto.AdverseEvent)(nil),
	(*allergy_intolerance_go_proto.AllergyIntolerance)(nil),
	(*appointment_go_proto.Appointment)(nil),
	(*appointment_response_go_proto.AppointmentResponse)(nil),
	(*audit_event_go_proto.AuditEvent)(nil),
	(*basic_go_proto.Basic)(nil),
	(*biologically_derived_product_go_proto.BiologicallyDerivedProduct)(nil),
	(*body_structure_go_proto.BodyStructure)(nil),
	(*capability_statement_go_proto.CapabilityStatement)(nil),
	(*care_plan_go_proto.CarePlan)(nil),
	(*care_team_go_proto.CareTeam)(nil),
	(*catalog_entry_go_proto.CatalogEntry)(nil),
	(*charge_item_go_proto.ChargeItem)(nil),
	(*charge_item_definition_go_proto.ChargeItemDefinition)(nil),
	(*claim_go_proto.Claim)(nil),
	(*claim_response_go_proto.ClaimResponse)(nil),
	(*clinical_impression_go_proto.ClinicalImpression)(nil),
	(*code_system_go_proto.CodeSystem)(nil),
	(*communication_go_proto.Communication)(nil),
	(*communication_request_go_proto.CommunicationRequest)(nil),
	(*compartment_definition_go_proto.CompartmentDefinition)(nil),
	(*composition_go_proto.Composition)(nil),
	(*concept_map_go_proto.ConceptMap)(nil),
	(*condition_go_proto.Condition)(nil),
	(*consent_go_proto.Consent)(nil),
	(*contract_go_proto.Contract)(nil),
	(*coverage_go_proto.Coverage)(nil),
	(*coverage_eligibility_request_go_proto.CoverageEligibilityRequest)(nil),
	(*coverage_eligibility_response_go_proto.CoverageEligibilityResponse)(nil),
	(*detected_issue_go_proto.DetectedIssue)(nil),
	(*device_go_proto.Device)(nil),
	(*device_definition_go_proto.DeviceDefinition)(nil),
	(*device_metric_go_proto.DeviceMetric)(nil),
	(*device_request_go_proto.DeviceRequest)(nil),
	(*device_use_statement_go_proto.DeviceUseStatement)(nil),
	(*diagnostic_report_go_proto.DiagnosticReport)(nil),
	(*document_manifest_go_proto.DocumentManifest)(nil),
	(*document_reference_go_proto.DocumentReference)(nil),
	(*effect_evidence_synthesis_go_proto.EffectEvidenceSynthesis)(nil),
	(*encounter_go_proto.Encounter)(nil),
	(*endpoint_go_proto.Endpoint)(nil),
	(*enrollment_request_go_proto.EnrollmentRequest)(nil),
	(*enrollment_response_go_proto.EnrollmentResponse)(nil),
	(*episode_of_care_go_proto.EpisodeOfCare)(nil),
	(*event_definition_go_proto.EventDefinition)(nil),
	(*evidence_go_proto.Evidence)(nil),
	(*evidence_variable_go_proto.EvidenceVariable)(nil),
	(*example_scenario_go_proto.ExampleScenario)(nil),
	(*explanation_of_benefit_go_proto.ExplanationOfBenefit)(nil),
	(*family_member_history_go_proto.FamilyMemberHistory)(nil),
	(*flag_go_proto.Flag)(nil),
	(*goal_go_proto.Goal)(nil),
	(*graph_definition_go_proto.GraphDefinition)(nil),
	(*group_go_proto.Group)(nil),
	(*guidance_response_go_proto.GuidanceResponse)(nil),
	(*healthcare_service_go_proto.HealthcareService)(nil),
	(*imaging_study_go_proto.ImagingStudy)(nil),
	(*immunization_go_proto.Immunization)(nil),
	(*immunization_evaluation_go_proto.ImmunizationEvaluation)(nil),
	(*immunization_recommendation_go_proto.ImmunizationRecommendation)(nil),
	(*implementation_guide_go_proto.ImplementationGuide)(nil),
	(*insurance_plan_go_proto.InsurancePlan)(nil),
	(*invoice_go_proto.Invoice)(nil),
	(*library_go_proto.Library)(nil),
	(*linkage_go_proto.Linkage)(nil),
	(*list_go_proto.List)(nil),
	(*location_go_proto.Location)(nil),
	(*measure_go_proto.Measure)(nil),
	(*measure_report_go_proto.MeasureReport)(nil),
	(*media_go_proto.Media)(nil),
	(*medication_go_proto.Medication)(nil),
	(*medication_administration_go_proto.MedicationAdministration)(nil),
	(*medication_dispense_go_proto.MedicationDispense)(nil),
	(*medication_knowledge_go_proto.MedicationKnowledge)(nil),
	(*medication_request_go_proto.MedicationRequest)(nil),
	(*medication_statement_go_proto.MedicationStatement)(nil),
	(*medicinal_product_go_proto.MedicinalProduct)(nil),
	(*medicinal_product_authorization_go_proto.MedicinalProductAuthorization)(nil),
	(*medicinal_product_contraindication_go_proto.MedicinalProductContraindication)(nil),
	(*medicinal_product_indication_go_proto.MedicinalProductIndication)(nil),
	(*medicinal_product_ingredient_go_proto.MedicinalProductIngredient)(nil),
	(*medicinal_product_interaction_go_proto.MedicinalProductInteraction)(nil),
	(*medicinal_product_manufactured_go_proto.MedicinalProductManufactured)(nil),
	(*medicinal_product_packaged_go_proto.MedicinalProductPackaged)(nil),
	(*medicinal_product_pharmaceutical_go_proto.MedicinalProductPharmaceutical)(nil),
	(*medicinal_product_undesirable_effect_go_proto.MedicinalProductUndesirableEffect)(nil),
	(*message_definition_go_proto.MessageDefinition)(nil),
	(*message_header_go_proto.MessageHeader)(nil),
	(*molecular_sequence_go_proto.MolecularSequence)(nil),
	(*naming_system_go_proto.NamingSystem)(nil),
	(*nutrition_order_go_proto.NutritionOrder)(nil),
	(*observation_go_proto.Observation)(nil),
	(*observation_definition_go_proto.ObservationDefinition)(nil),
	(*operation_definition_go_proto.OperationDefinition)(nil),
	(*operation_outcome_go_proto.OperationOutcome)(nil),
	(*organization_go_proto.Organization)(nil),
	(*organization_affiliation_go_proto.OrganizationAffiliation)(nil),
	(*patient_go_proto.Patient)(nil),
	(*payment_notice_go_proto.PaymentNotice)(nil),
	(*payment_reconciliation_go_proto.PaymentReconciliation)(nil),
	(*person_go_proto.Person)(nil),
	(*plan_definition_go_proto.PlanDefinition)(nil),
	(*practitioner_go_proto.Practitioner)(nil),
	(*practitioner_role_go_proto.PractitionerRole)(nil),
	(*procedure_go_proto.Procedure)(nil),
	(*provenance_go_proto.Provenance)(nil),
	(*questionnaire_go_proto.Questionnaire)(nil),
	(*questionnaire_response_go_proto.QuestionnaireResponse)(nil),
	(*related_person_go_proto.RelatedPerson)(nil),
	(*request_group_go_proto.RequestGroup)(nil),
	(*research_definition_go_proto.ResearchDefinition)(nil),
	(*research_element_definition_go_proto.ResearchElementDefinition)(nil),
	(*research_study_go_proto.ResearchStudy)(nil),
	(*research_subject_go_proto.ResearchSubject)(nil),
	(*risk_assessment_go_proto.RiskAssessment)(nil),
	(*risk_evidence_synthesis_go_proto.RiskEvidenceSynthesis)(nil),
	(*schedule_go_proto.Schedule)(nil),
	(*search_parameter_go_proto.SearchParameter)(nil),
	(*service_request_go_proto.ServiceRequest)(nil),
	(*slot_go_proto.Slot)(nil),
	(*specimen_go_proto.Specimen)(nil),
	(*specimen_definition_go_proto.SpecimenDefinition)(nil),
	(*structure_definition_go_proto.StructureDefinition)(nil),
	(*structure_map_go_proto.StructureMap)(nil),
	(*subscription_go_proto.Subscription)(nil),
	(*substance_go_proto.Substance)(nil),
	(*substance_nucleic_acid_go_proto.SubstanceNucleicAcid)(nil),
	(*substance_polymer_go_proto.SubstancePolymer)(nil),
	(*substance_protein_go_proto.SubstanceProtein)(nil),
	(*substance_reference_information_go_proto.SubstanceReferenceInformation)(nil),
	(*substance_source_material_go_proto.SubstanceSourceMaterial)(nil),
	(*substance_specification_go_proto.SubstanceSpecification)(nil),
	(*supply_delivery_go_proto.SupplyDelivery)(nil),
	(*supply_request_go_proto.SupplyRequest)(nil),
	(*task_go_proto.Task)(nil),
	(*terminology_capabilities_go_proto.TerminologyCapabilities)(nil),
	(*test_report_go_proto.TestReport)(nil),
	(*test_script_go_proto.TestScript)(nil),
	(*value_set_go_proto.ValueSet)(nil),
	(*verification_result_go_proto.VerificationResult)(nil),
	(*vision_prescription_go_proto.VisionPrescription)(nil),
	(*parameters_go_proto.Parameters)(nil),
	(*binary_go_proto.Binary)(nil),
	(*bundle_and_contained_resource_go_proto.Bundle)(nil),
}

// dummyElements is an array of nil pointers to all Element messages.
var dummyElements = []proto.Message{
	(*datatypes_go_proto.Address)(nil),
	(*datatypes_go_proto.Age)(nil),
	(*datatypes_go_proto.Annotation)(nil),
	(*datatypes_go_proto.Attachment)(nil),
	(*datatypes_go_proto.Base64Binary)(nil),
	(*datatypes_go_proto.Boolean)(nil),
	(*datatypes_go_proto.Canonical)(nil),
	(*datatypes_go_proto.Code)(nil),
	(*datatypes_go_proto.CodeableConcept)(nil),
	(*datatypes_go_proto.Coding)(nil),
	(*datatypes_go_proto.ContactDetail)(nil),
	(*datatypes_go_proto.ContactPoint)(nil),
	(*datatypes_go_proto.Contributor)(nil),
	(*datatypes_go_proto.Count)(nil),
	(*datatypes_go_proto.DataRequirement)(nil),
	(*datatypes_go_proto.Date)(nil),
	(*datatypes_go_proto.DateTime)(nil),
	(*datatypes_go_proto.Decimal)(nil),
	(*datatypes_go_proto.Distance)(nil),
	(*datatypes_go_proto.Dosage)(nil),
	(*datatypes_go_proto.Duration)(nil),
	(*datatypes_go_proto.ElementDefinition)(nil),
	(*datatypes_go_proto.Expression)(nil),
	(*datatypes_go_proto.Extension)(nil),
	(*datatypes_go_proto.HumanName)(nil),
	(*datatypes_go_proto.Id)(nil),
	(*datatypes_go_proto.Identifier)(nil),
	(*datatypes_go_proto.Instant)(nil),
	(*datatypes_go_proto.Integer)(nil),
	(*datatypes_go_proto.Markdown)(nil),
	(*datatypes_go_proto.MarketingStatus)(nil),
	(*datatypes_go_proto.Meta)(nil),
	(*datatypes_go_proto.Money)(nil),
	(*datatypes_go_proto.MoneyQuantity)(nil),
	(*datatypes_go_proto.Narrative)(nil),
	(*datatypes_go_proto.Oid)(nil),
	(*datatypes_go_proto.ParameterDefinition)(nil),
	(*datatypes_go_proto.Period)(nil),
	(*datatypes_go_proto.PositiveInt)(nil),
	(*datatypes_go_proto.ProductShelfLife)(nil),
	(*datatypes_go_proto.Quantity)(nil),
	(*datatypes_go_proto.Range)(nil),
	(*datatypes_go_proto.Ratio)(nil),
	(*datatypes_go_proto.Reference)(nil),
	(*datatypes_go_proto.RelatedArtifact)(nil),
	(*datatypes_go_proto.SampledData)(nil),
	(*datatypes_go_proto.Signature)(nil),
	(*datatypes_go_proto.SimpleQuantity)(nil),
	(*datatypes_go_proto.String)(nil),
	(*datatypes_go_proto.Time)(nil),
	(*datatypes_go_proto.Timing)(nil),
	(*datatypes_go_proto.TriggerDefinition)(nil),
	(*datatypes_go_proto.UnsignedInt)(nil),
	(*datatypes_go_proto.Uri)(nil),
	(*datatypes_go_proto.Url)(nil),
	(*datatypes_go_proto.UsageContext)(nil),
	(*datatypes_go_proto.Uuid)(nil),
	(*datatypes_go_proto.Xhtml)(nil),
}
